version: '3.8'

volumes:
  db:
  redis-data:

services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - kafka-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  redis:
    container_name: redis
    image: 'redis:latest'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - kafka-network

networks:
  kafka-network:
    name: kafkastart